// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.wpilibj.RobotBase;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.button.RobotModeTriggers;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine.Direction;
import frc.robot.commands.RotateToTargetCommand;
import frc.robot.commands.ShooterTestCommand;
import frc.robot.generated.TunerConstants;
import frc.robot.sim.JoystickInputsRecord;
import frc.robot.sim.ShowVisionOnField;
import frc.robot.sim.SimWrapper;
import frc.robot.subsystems.CommandSwerveDrivetrain;
import frc.robot.subsystems.ShooterSubsystem;
import frc.robot.subsystems.auto.AutoLogic;
import frc.robot.visutils.DriveSmooth;
import frc.robot.visutils.LimelightOdometry;
import frc.robot.visutils.AllianceCalc;
import frc.robot.visutils.DriveAccuracyTester;
import frc.robot.visutils.MotionlessTracker;
import frc.robot.visutils.TurnToAngleHelper;
import frc.robot.visutils.VisionKalmanFilter;

/**
 * The RobotContainer class is where the bulk of the robot structure is declared.
 *
 * <p>This class centralizes the hardware instances, UI device bindings, and
 * the mapping between operator inputs and subsystem commands for the 2026 season.
 */
public class RobotContainer {

    /** Maximum linear velocity of the robot in meters per second. */
    private double MaxSpeed = TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
    /** Maximum angular velocity of the robot in radians per second. */
    private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond);

    /** Maximum linear velocity of the robot DURING TELEOP in meters per second. */
    private double TeleoperatedSpeed = Math.min(TunerConstants.kSpeedInTeleop.in(MetersPerSecond), MaxSpeed);

    /** Standard field-centric swerve request. Uses Velocity control for smoother movement.
     *  Near-zero deadband catches floating-point residuals only;
     *  main joystick deadband and smoothing is handled by DriveSmooth. */
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(0.001 * TeleoperatedSpeed)
            .withRotationalDeadband(0.001 * MaxAngularRate)
            .withDriveRequestType(DriveRequestType.Velocity);

    /** Brake request: Forces all modules into an X-pattern to resist movement. */
    private final SwerveRequest.SwerveDriveBrake brake = new SwerveRequest.SwerveDriveBrake();
    /** Point request: Orients all modules toward a specific direction without driving. */
    private final SwerveRequest.PointWheelsAt point = new SwerveRequest.PointWheelsAt();

    /** Telemetry helper for logging drivetrain state to AdvantageScope/Dashboard. */
    private final Telemetry logger = new Telemetry(MaxSpeed);

    /** Primary driver controller (Port 0). */
    private final CommandXboxController driveController = new CommandXboxController(0);
    /** Primary operator controller (Port 1). */
    private final CommandXboxController operateController = new CommandXboxController(1);

    /** Joystick processing pipeline: deadband + response curve + slew-rate limiting. */
    private final DriveSmooth m_driveSmooth = new DriveSmooth();

    /** The drivetrain subsystem, initialized using constants generated by Tuner X. */
    public final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();

    public final BasicInfoDashboard basicInfoDashboard = new BasicInfoDashboard(drivetrain);

    /** Field2d for Glass/SmartDashboard visualization. */
    public final Field2d m_glassField = new Field2d();

    /** Simulation wrapper - null when not in simulation. */
    public final SimWrapper m_simWrapper;
    public final ShowVisionOnField m_showVisionOnField;

    /** Manages the tape-drop accuracy test workflow. */
    public final DriveAccuracyTester m_driveAccuracyTester;

    public final LimelightOdometry m_limelightOdometry;

    public final ShooterSubsystem shooterSubsystem = new ShooterSubsystem();

    /** Vision-only Kalman filter for precise stationary position estimation. */
    public final VisionKalmanFilter m_visionKalmanFilter = new VisionKalmanFilter();

    /** Tracks whether the robot is motionless and for how long. */
    public final MotionlessTracker m_motionlessTracker;

    /**
     * Constructs the RobotContainer.
     * Initializes autonomous selection dashboards and binds controller inputs to commands.
     */
    public RobotContainer() {
        Field2d debugField = null;

        SmartDashboard.putData("GlassField", m_glassField);

        AutoLogic.initShuffleboard(drivetrain);
        m_driveAccuracyTester = new DriveAccuracyTester(
            drivetrain, m_visionKalmanFilter, basicInfoDashboard::forceDisableVision);

        // Add a button on dashboard to launch Accuracy Drive Test
        SmartDashboard.putData("Accuracy Drive Test", m_driveAccuracyTester.createTapeDropAutoCommand());

        configureBindings();

        // $VISIONSIM - Wrapper for sim features
        if (Robot.isSimulation()) {
            m_simWrapper = new SimWrapper(
                drivetrain,
                this::resetRobotPose);

            debugField = m_simWrapper.getSimDebugField();
        }
        else {
            m_simWrapper = null;
        }

        m_showVisionOnField = new ShowVisionOnField(
            m_glassField, debugField);

        // Setup vision system
        m_motionlessTracker = new MotionlessTracker(() -> drivetrain.getState().Speeds);
        m_motionlessTracker.setOnStartedMoving(m_visionKalmanFilter::reset);

        m_limelightOdometry = new LimelightOdometry(drivetrain::addVisionMeasurement);
        m_limelightOdometry.setVisionDependencies(
            basicInfoDashboard::isVisionEnabled,
            m_visionKalmanFilter,
            m_motionlessTracker::isMotionless);

        basicInfoDashboard.setVisionDependencies(
            m_limelightOdometry::getCurrentConfidenceScore,
            m_limelightOdometry::getNumLockedTags,
            m_limelightOdometry::getTx,
            m_limelightOdometry::getTargetList,
            m_motionlessTracker::isMotionless,
            m_motionlessTracker::getSecondsStill);

        basicInfoDashboard.setVisionKalmanSupplier(() -> m_visionKalmanFilter);
    }

    /**
     * Processes raw joystick input for translation (X-axis).
     * Pipeline: deadband+rescale → response curve → slew-rate limit → speed scale.
     *
     * @return Scaled velocity in meters per second.
     */
    private double getDriveX() {
        double input = m_driveSmooth.processTranslationX(-driveController.getLeftY());
        // Reduce speed by 50% if the Right Bumper is held for fine positioning
        double inputScale = driveController.rightBumper().getAsBoolean() ? 0.5 : 1.0;
        return input * TeleoperatedSpeed * inputScale;
    }

    /**
     * Processes raw joystick input for translation (Y-axis).
     * Pipeline: deadband+rescale → response curve → slew-rate limit → speed scale.
     *
     * @return Scaled velocity in meters per second.
     */
    private double getDriveY() {
        double input = m_driveSmooth.processTranslationY(-driveController.getLeftX());
        double inputScale = driveController.rightBumper().getAsBoolean() ? 0.5 : 1.0;
        return input * TeleoperatedSpeed * inputScale;
    }

    /**
     * Processes raw joystick input for rotation.
     * Pipeline: deadband+rescale → response curve → slew-rate limit → speed scale.
     *
     * @return Scaled angular velocity in radians per second.
     */
    private double getDriveRotate() {
        double input = m_driveSmooth.processRotation(-driveController.getRightX());
        double inputScale = driveController.rightBumper().getAsBoolean() ? 0.5 : 1.0;
        return input * MaxAngularRate * inputScale;
    }

    /**
     * Defines trigger-to-command mappings.
     */
    private void configureBindings() {
        // Set the default command for the drivetrain to follow joystick inputs continuously.
        // When POV-UP is held, rotation locks onto AprilTag 26 while X/Y remain free.
        final double[] aimTarget = TurnToAngleHelper.resolveTagTarget(Constants.VisionConstants.kTurnToTagID);

        drivetrain.setDefaultCommand(
            drivetrain.applyRequest(() -> {
                double leftX = getDriveX();
                double leftY = getDriveY();
                double rightX = getDriveRotate();

                // $VISIONSIM - Wrapper for sim features
                if (Robot.isSimulation()) {
                    JoystickInputsRecord newJoystickInputs =

                        SimWrapper.transformJoystickOrientation(
                        drivetrain.getOperatorForwardDirection().getDegrees(),
                        leftX,
                        leftY,
                        rightX);
                    leftX = -1 * newJoystickInputs.driveX();
                    leftY = -1 * newJoystickInputs.driveY();
                    rightX = newJoystickInputs.rotatetX();
                }

                return drive.withVelocityX(leftX)
                     .withVelocityY(leftY)
                     .withRotationalRate(rightX);
            })
        );

        //shooterSubsystem.setDefaultCommand(new ShooterTestCommand(shooterSubsystem, operateController));

        // Keep the drivetrain in an Idle state while the robot is disabled
        final var idle = new SwerveRequest.Idle();
        RobotModeTriggers.disabled().whileTrue(
            drivetrain.applyRequest(() -> idle).ignoringDisable(true)
        );

        // Map Button A to the brake command for defensive positioning
        driveController.a().whileTrue(drivetrain.applyRequest(() -> brake));

        // Map Button B to orient wheels based on the left joystick angle (useful for testing)
        driveController.b().whileTrue(drivetrain.applyRequest(() ->
            point.withModuleDirection(new Rotation2d(-driveController.getLeftY(), -driveController.getLeftX()))
        ));

        // SysId Characterization bindings (Back/Start + X/Y) for automated PID tuning
        driveController.back().and(driveController.y()).whileTrue(drivetrain.sysIdDynamic(Direction.kForward));
        driveController.back().and(driveController.x()).whileTrue(drivetrain.sysIdDynamic(Direction.kReverse));
        driveController.start().and(driveController.y()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kForward));
        driveController.start().and(driveController.x()).whileTrue(drivetrain.sysIdQuasistatic(Direction.kReverse));

        // Recalibrate the gyro's forward heading using the Left Bumper
        driveController.leftBumper().onTrue(drivetrain.runOnce(() -> drivetrain.seedFieldCentric()));
        
        // Try to align to an AprilTag with the Left Trigger
        driveController.leftTrigger().onTrue(drivetrain.runOnce(() -> drivetrain.AlignToTag(driveController, MaxAngularRate)));

        // $VISIONSIM - POV buttons for sim
        if (Robot.isSimulation()) {
            // In simulation, inject drift with POV right to test vision correction
            driveController.povRight()
                .onTrue(drivetrain.runOnce(() -> m_simWrapper.injectDrift(0.5, 15.0)));

            // POV left resets robot to the starting pose of the selected auto
            driveController.povLeft().onTrue(
                drivetrain
                    .runOnce(() -> m_simWrapper.cycleResetPosition(AutoLogic.getSelectedAutoStartingPose())));
        }

        // Hook up the telemetry logger to the drivetrain periodic updates
        drivetrain.registerTelemetry(logger::telemeterize);

        // POV Down: rotate in place to face the configured AprilTag
        driveController.povDown().whileTrue(
            new RotateToTargetCommand(drivetrain, Constants.VisionConstants.kTurnToTagID));
    }

    /**
     * Wrapper for team-specific commands to handle simulation behavior.
     *
     * @param command The command to wrap.
     * @return The original command or an empty command if in simulation.
     */
    private Command CmdWrapperTeamCommand(Command command) {
        if (RobotBase.isSimulation()) {
            return Commands.none();
        }
        return command;
    }

    /**
     * Retrieves the autonomous routine selected via the dashboard at the start of the match.
     *
     * @return The command to execute during the autonomous period.
     */
    public Command getAutonomousCommand() {
        return AutoLogic.getSelectedAutoCommand();
    }

    /**
     * Called when the robot pose is reset in simulation.
     * This is triggered by GroundTruthSim via the consumer pattern.
     *
     * <p>Resets both the ground truth pose and the drivetrain pose to the specified pose.
     * Also resets the vision system simulation pose history if a Vision instance is set.
     *
     * @param pose The new pose the robot has been reset to
     */
    private void resetRobotPose(Pose2d pose) {
        System.out.println("Robot pose reset to: " + pose);

        drivetrain.resetPose(pose);

        // $VISIONSIM - Clean reset
        if (Robot.isSimulation()) {
            // NOTE: This is only reset in simulation since m_simWrapper isnt ever
            // instantiated in real mode.  This is because the pose we reset
            // here is the ground truth pose which is only relevent in simulation.
            m_simWrapper.resetSimPose(pose);
        }

        // Reset the vision-only Kalman filter
        m_visionKalmanFilter.reset();

        // Remove any tape from the field
        m_driveAccuracyTester.clearTape();
    }
}
